module.exports.runtime = {
  handler: async function ({ audit_type }) {
    try {
      const response = await fetch("http://127.0.0.1:8000/audit", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          audit_type: audit_type,
          jurisdiction: "default"
        })
      });
      const data = await response.json();
      // Returns the narrative summary generated by the Python engine
      return data.narrative || JSON.stringify(data); 
    } catch (e) {
      return `Axoworks Engine Error: ${e.message}`;
    }
  }
};